#!/bin/bash
#SBATCH --job-name=ewas     # job name in the queue
#SBATCH --time=01:00:00     # wall time
#SBATCH --ntasks=1          # number of tasks (e.g. MPI processes)
#SBATCH --cpus-per-task=1   # number of threads per task (e.g. OpenMP)
#SBATCH --mem=8G            # amount of memory to request

export GA4GH_PORT=10083  # port must not in use by other users, make sure it is the same port your forwarded to the cluster
export GA4GH_IMG=${PWD}/ga4gh_nesi.img  # path to the GA4GH singularity image you uploaded
export GA4GH_TEMP=${PWD}/temp

# should not need to edit below this line

# load singularity module
module load Singularity

# set up port forwarding between node that submitted job to compute node it is running on
echo "GA4GH will be started on $(hostname) and port forwarding established from $SLURM_SUBMIT_HOST on port ${GA4GH_PORT}"
ssh -N -R ${GA4GH_PORT}:localhost:${GA4GH_PORT} $SLURM_SUBMIT_HOST &

# make sure directories exist
mkdir -p $GA4GH_TEMP

# create the myports.conf with custom port
cat << EOF > myports.conf
Listen $GA4GH_PORT

<IfModule ssl_module>
        Listen 443
</IfModule>

<IfModule mod_gnutls.c>
        Listen 443
</IfModule>

EOF

singularity run --writable-tmpfs --no-home -B ${GA4GH_TEMP}:/var/run/apache2/,${REGISTRY_PATH}:/registry,${PWD}/myports.conf:/etc/apache2/ports.conf ga4gh_nesi.img  $@

